quarkus.http.port=8080
quarkus.http.cors.enabled=true
quarkus.http.cors.origins=http://localhost:3000,http://localhost:3001
quarkus.http.cors.methods=GET,POST,OPTIONS
quarkus.http.cors.headers=Content-Type,X-Request-Id,If-None-Match
quarkus.http.cors.exposed-headers=ETag

quarkus.datasource.db-kind=postgresql
quarkus.hibernate-orm.schema-management.strategy=validate
quarkus.flyway.migrate-at-start=true

%prod.quarkus.datasource.jdbc.url=${TLOM_DB_URL}
%prod.quarkus.datasource.username=${TLOM_DB_USERNAME}
%prod.quarkus.datasource.password=${TLOM_DB_PASSWORD}

%dev.quarkus.datasource.devservices.enabled=true
%test.quarkus.datasource.devservices.enabled=true
